### ISSUE TITLE
No 'id_to_label.json' when trying to create wlasl landmarks dataset

### ISSUE THREAD

**Issue by JChaloton** [xmartlabs/spoter-embeddings#4]
Good day to you

A I tried to run the 'preprocessing.py' The error showed:

`Traceback (most recent call last):
  File "/home/jirapong/spoter-embeddings/preprocessing.py", line 17, in <module>
    create(args)
  File "/home/user/spoter-embeddings/preprocessing/create_wlasl_landmarks_dataset.py", line 79, in create
    shutil.copy(os.path.join(BASE_DATA_FOLDER, 'wlasl/id_to_label.json'), dataset_folder)
  File "/home/user/anaconda3/envs/mediapipe/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/user/anaconda3/envs/mediapipe/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'data/wlasl/id_to_label.json'
`

May I know where can I find the 'id_to_label.json' file?

Thank you in advance!

**Comment by mats-claassen** [comment]
Hi @JChaloton the id_to_label.json file maps the class id to the class name. For ease of use I am pushing that into the data/wlasl folder, so you should get it if you pull the latest changes.

**Comment by JChaloton** [comment]
Thank you for your quick response! I got them now. Please keep up the good work!
