### ISSUE TITLE
ValueError: Input X contains NaN.

### ISSUE THREAD

**Issue by JChaloton** [xmartlabs/spoter-embeddings#6]
Hello author.
After I tried to run the model from the preprocessing dataset provided by the spoter repo, this error occured:

2024-11-08 21:28:05,037 - test1 - INFO - Starting test1...

 (train.py:177)
2024-11-08 21:29:33,546 - test1 - INFO - Epoch time: 0:01:28.508812 (train.py:236)
2024-11-08 21:29:33,546 - test1 - INFO - [1] TRAIN  loss: 0.9961132860702017 acc: -0.12751664 (train.py:237)
2024-11-08 21:29:33,546 - test1 - INFO - [1] VALIDATION  acc: -0.40953693 (train.py:238)
2024-11-08 21:31:19,953 - test1 - INFO - Epoch time: 0:01:46.401303 (train.py:236)
2024-11-08 21:31:19,953 - test1 - INFO - [2] TRAIN  loss: 1.0028270651464877 acc: -0.14162065 (train.py:237)
2024-11-08 21:31:19,954 - test1 - INFO - [2] VALIDATION  acc: -0.43123114 (train.py:238)
Traceback (most recent call last):
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jirapong/spoteremb/spoter-embeddings/train.py", line 286, in <module>
    train(args, tracker)
  File "/home/jirapong/spoteremb/spoter-embeddings/train.py", line 198, in train
    train_loss, val_silhouette_coef = train_epoch_embedding(**train_kwargs)
  File "/home/jirapong/spoteremb/spoter-embeddings/models/utils.py", line 62, in train_epoch_embedding
    val_silhouette_coef = evaluate_embedding(model, val_loader, device)
  File "/home/jirapong/spoteremb/spoter-embeddings/models/utils.py", line 202, in evaluate_embedding
    silhouette_coefficient = silhouette_score(
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/site-packages/sklearn/metrics/cluster/_unsupervised.py", line 130, in silhouette_score
    return np.mean(silhouette_samples(X, labels, metric=metric, **kwds))
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 187, in wrapper
    return func(*args, **kwargs)
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/site-packages/sklearn/metrics/cluster/_unsupervised.py", line 257, in silhouette_samples
    X, labels = check_X_y(X, labels, accept_sparse=["csr"])
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1146, in check_X_y
    X = check_array(
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/site-packages/sklearn/utils/validation.py", line 957, in check_array
    _assert_all_finite(
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/site-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/home/jirapong/anaconda3/envs/spoter-original/lib/python3.8/site-packages/sklearn/utils/validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.

This is my training hyperparameter:
`python -m train --experiment_name test1 --hard_triplet_mining None --training_set_path /home/jirapong/spoteremb/spoter-embeddings//datasets/WLASL100_train_25fps.csv --validation_set_path /home/jirapong/spoteremb/spoter-embeddings//datasets/WLASL100_val_25fps.csv --epochs 30
`

May I ask what would be the cause?
I have also tried creating a landmark model from the WLASL preprocess file. This one finished the whole training but it has the problem that the accuracy value stays the same for every epochs.

Looking forward to hear from you!

**Comment by mats-claassen** [comment]
Hi @JChaloton could you share your Python environment? Did you install the dependencies as specified in this project or did you update some of them?

**Comment by JChaloton** [comment]
Hello author! I have re-checked my Python environment and other dependencies and I indeed updated some of them. After I tried to follow the specified environments and dependencies version I got them to work now.

However, When I tried to train using the hyperparameter in the train.sh with 350 epochs, and the dataset provided by the [spoter](https://github.com/matyasbohacek/spoter/releases/tag/supplementary-data) repository. I got a very low accuracy.
`2024-11-14 11:59:02,492 - lr001-350 - INFO - Epoch time: 0:00:21.673032 (train.py:236)
2024-11-14 11:59:02,492 - lr001-350 - INFO - [350] TRAIN  loss: 0.8832609857122103 acc: 0.046199974 (train.py:237)
2024-11-14 11:59:02,492 - lr001-350 - INFO - [350] VALIDATION  acc: -0.16928874 (train.py:238)
`

So I made a custom dataset from the preprocessed WLASL with the mediapipe provided in your repository. It also has the same the same outcome.
`2024-11-14 14:28:26,266 - wlasl-mediapipe-lr001-350 - INFO - Epoch time: 0:00:22.992259 (train.py:236)
2024-11-14 14:28:26,267 - wlasl-mediapipe-lr001-350 - INFO - [350] TRAIN  loss: 0.5813686764836311 acc: 0.32490766 (train.py:237)
2024-11-14 14:28:26,267 - wlasl-mediapipe-lr001-350 - INFO - [350] VALIDATION  acc: 0.04370387 (train.py:238)
`

I have tried to change the learning rate to 0.0001 and epochs to 500 but the result is still very low.
`2024-11-14 03:12:18,796 - change-epoch350 - INFO - Epoch time: 0:00:21.406186 (train.py:236)
2024-11-14 03:12:18,796 - change-epoch350 - INFO - [500] TRAIN  loss: 1.0522077899509006 acc: -0.12269192 (train.py:237)
2024-11-14 03:12:18,796 - change-epoch350 - INFO - [500] VALIDATION  acc: -0.2771219 (train.py:238)
`

May I ask what could be the problem?

**Comment by mats-claassen** [comment]
Hey @JChaloton when using the embedding model, the metric used to evaluate it is [silhouette](https://en.wikipedia.org/wiki/Silhouette_(clustering)) (not classification accuracy) as the logs might misleadingly imply.
Silhouette coefficient goes from -1 to 1, where 1 is best.

As stated in the Readme our best model reaches 0.7 on train dataset and 0.1 in validation set. 
<img width="518" alt="Screenshot 2024-11-20 at 15 50 18" src="https://github.com/user-attachments/assets/bf3aefce-c813-4292-9307-92eb0b7d8941">

So while it looks like your metrics can still improve, they are on the same way as our results. The `create_embedding_scatter_plots` function can be used for visualizing the clusters post-training

**Comment by JChaloton** [comment]
Oh I see it now! Thank you very much author.
